#!/usr/bin/env python3
#Project-Clean
#By-JoyGhosh
import os
import sys
execute=os.system
filter=sys.argv[1]
#Patterns
juicy="redirect=|debug|password|passwd|file=|logs|file|fn|include|require|callback|href"
xss="q=|s=|search=|lang=|keyword=|query=|page=|keywords=|year=|view=|email=|type=|name=|p=|callback=|jsonp=|api_key=|api=|password=|email=|emailto=|token=|username=|csrf_token=|unsubscribe_token=|id=|item=|page_id=|month=|immagine=|list_type=|url=|terms=|categoryid=|key=|l=|begindate=|enddate="
lfi="file=|document=|folder=|root=|path=|pg=|style=|pdf=|template=|php_path=|doc=|page=|name=|cat=|dir=|action=|board=|date=|detail=|download=|prefix=|include=|inc=|locate=|show=|site=|type=|view=|content=|layout=|mod=|conf=|url="
debug="access=|admin=|dbg=|debug=|edit=|grant=|test=|alter=|clone=|create=|delete=|disable=|enable=|exec=|execute=|load=|make=|modify=|rename=|reset=|shell=|toggle=|adm=|root=|cfg=|config="
ssrf="access=|admin=|dbg=|debug=|edit=|grant=|test=|alter=|clone=|create=|delete=|disable=|enable=|exec=|execute=|load=|make=|modify=|rename=|reset=|shell=|toggle=|adm=|root=|cfg=|dest=|redirect=|uri=|path=|continue=|url=|window=|next=|data=|reference=|site=|html=|val=|validate=|domain=|callback=|return=|page=|feed=|host=|port=|to=|out=|view=|dir=|show=|navigation=|open=|file=|document=|folder=|pg=|php_path=|style=|doc=|img=|filename="
redirect="image_url=|Open=|callback=|cgi-bin/redirect.cgi|cgi-bin/redirect.cgi?|checkout=|checkout_url=|continue=|data=|dest=|destination=|dir=|domain=|feed=|file=|file_name=|file_url=|folder=|folder_url=|forward=|from_url=|go=|goto=|host=|html=|image_url=|img_url=|load_file=|load_url=|login?to=|login_url=|logout=|navigation=|next=|next_page=|out=|page=|page_url=|path=|port=|redir=|redirect=|redirect_to=|redirect_uri=|redirect_url=|reference=|return=|returnTo=|return_path=|return_to=|return_url=|rt=|rurl=|show=|site=|target=|to=|uri=|url=|val=|validate=|view=|window="
img="=.*.jpg|=.*.jpeg|=.*.gif|=.*.png"
ssti="template=|preview=|id=|view=|activity=|name=|content=|redirect="
idor="'id=|user=|account=|number=|order=|no=|doc=|key=|email=|group=|profile=|edit=|report='"
ip="'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'"
url="'((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+'"
sql="id=|select=|report=|role=|update=|query=|user=|name=|sort=|where=|search=|params=|process=|row=|view=|table=|from=|sel=|results=|sleep=|fetch=|order=|keyword=|column=|field=|delete=|string=|number=|filter="
confi="accesskey|admin|aes|api_key|apikey|checkClientTrusted|crypt|password|pinning|secret|SHA256|SharedPreferences|superuser|token|X509TrustManager|insert"
rce="daemon=|upload=|dir=|download=|log=|ip=|cli=|cmd=|exec=|command=|execute=|ping=|query=|jump=|code=|reg=|do=|func=|arg=|option=|load=|process=|step=|read=|function|req=|feature=|exe=|module=|payload=|run=|print="
#PATTERNS_ENDS_HERE
#Flags
po="grep -Po"
ie="grep -iE"
eo="grep -Eo"
#Flags_Ends_Here
if filter=="url":
    execute(po+" "+url)
elif filter=="ip":
    execute(eo+" "+ip)
elif filter=="ssrf":
    execute(ie+" "+ssrf)
elif filter=="xss":
    execute(ie+" "+xss)
elif filter=="sql":
    execute(ie+" "+sql)
elif filter=="rce":
    execute(ie+" "+rce)
elif filter=="confidential":
    execute(ie+" "+confi)
elif filter=="redirect":
    execute(ie+" "+redirect)
elif filter=="debug":
    execute(ie+" "+redirect)
elif filter=="juicy":
    execute(ie+" "+juicy)
elif filter=="lfi":
    execute(ie+" "+lfi)
elif filter=="idor":
    execute(ie+" "+idor)
elif filter=="ssti":
    execute(ie+" "+ssti)
elif filter=="trav":
    execute(ie+" "+img)
elif filter=="help":
    print("""
    patterns                       description
    --------                      -------------
    url                       filter all url from stdin
    ip                        filter all ip  from stdin
    ssrf                      filter all ssrf parameter from stdin
    xss                       filter all xss parameter from stdin
    sql                       filter all sql parameter from stdin
    rce                       filter all rce parameter from stdin
    confidential              filter all confidential parameter from stdin
    redirect                  filter all redirect parameter from stdin
    idor                      filter all idor parameter from stdin
    debug                     filter all debug logic from stdin
    juicy                     filter all juicy parameter from stdin
    lfi                       filter all lfi parameter from stdin
    ssti                      filter all ssti parameter from stdin
    trav                      filter all img-traversal parameter from stdin
    """)

else:
    print("Filter not found type help to show available filters")
    exit()
