#!/usr/bin/env python3
import mmh3
import requests
import codecs
import sys
url=sys.argv[1]
response = requests.get('https://'+url+'/favicon.ico')
favicon = codecs.encode(response.content,"base64")
hash = mmh3.hash(favicon)
has=hash
print("http.favicon.hash:",has)
#USAGE : script.py domain.tld
