#!/usr/bin/env python3
import sys
import os
execute=os.system
try: 
    from googlesearch import search 
except ImportError:  
    print("No module named 'google' found installing it now")
    execute('pip3 install google')
query = sys.argv[1]
for j in search(query, tld='com', num=30, start=0, stop=None, pause=2.0): 
    print(j) 
