#!/bin/bash
function subjunks(){
maindomain=$(echo $1 | awk -F\. '{print $(NF-1) FS $NF}')
curl -sL $1 | grep -Po '((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+' | grep '.'$maindomain
}
for sub in $(cat $1 )
 do 
 subjunks $sub
 done
